[package]
name = "oscen"
version = "0.1.4"
edition = "2018"
authors = [
    "Reed Rosenbluth <reed.rosenbluth@gmail.com>", 
    "Jeffrey Rosenbluth <jeffrey.rosenbluth@gmail.com>",
    "Satya Bodduluri  <skbodduluri@gmail.com >",
]
repository = "https://github.com/reedrosenbluth/oscen"
documentation = "https://docs.rs/oscen/0.1.4/oscen/"
readme = "README.md"
license = "MIT OR Apache-2.0"
description = "A library for building modular synthesizers"
keywords = ["audio", "dsp", "synth", "synthesizer", "sound"]
categories = ["multimedia::audio"]

[dependencies]
approx = "0.3"
midir = "0.5"
num = "0.2"
pitch_calc = "0.12.0"
rand = "0.7"
rand_distr = "0.2"
libmath = "0.2.1"
crossbeam = "0.7"
parking_lot = "0.11"
