[package]
name = "swell"
version = "0.1.0"
authors = [
    "Satya Bodduluri  <skbodduluri@gmail.com >",
    "Reed Rosenbluth <reed.rosenbluth@gmail.com>", 
    "Jeffrey Rosenbluth <jeffrey.rosenbluth@gmail.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.13"
nannou_audio = "0.2"
crossbeam = "0.7.3"
libmath = "0.2.1"
derive_more = "0.99"
