[package]
name = "nannou-apps"
version = "0.1.0"
authors = [
    "Satya Bodduluri  <skbodduluri@gmail.com >",
    "Reed Rosenbluth <reed.rosenbluth@gmail.com>", 
    "Jeffrey Rosenbluth <jeffrey.rosenbluth@gmail.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
swell = { path = "../swell-lib" }
nannou = "0.14.1"
nannou_audio = "0.14"
midir = "0.5"
crossbeam = "0.7"
pitch_calc = "0.12.0"
rand = "0.7"